# Generated by Django 5.1.7 on 2025-03-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_etablissement_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
