# Generated by Django 5.1.7 on 2025-03-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_etablissement_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='telephone',
        ),
    ]
